// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestData.proto

package co.solinx.demo.serialize.protocolBuffer;

public final class TestDataProto {
  private TestDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocolBuffer.TestData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 sn = 1;</code>
     */
    boolean hasSn();
    /**
     * <code>required int32 sn = 1;</code>
     */
    int getSn();
  }
  /**
   * Protobuf type {@code protocolBuffer.TestData}
   */
  public static final class TestData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocolBuffer.TestData)
      TestDataOrBuilder {
    // Use TestData.newBuilder() to construct.
    private TestData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestData defaultInstance;
    public static TestData getDefaultInstance() {
      return defaultInstance;
    }

    public TestData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sn_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.solinx.demo.serialize.protocolBuffer.TestDataProto.internal_static_protocolBuffer_TestData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.solinx.demo.serialize.protocolBuffer.TestDataProto.internal_static_protocolBuffer_TestData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData.class, co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData.Builder.class);
    }

    public static com.google.protobuf.Parser<TestData> PARSER =
        new com.google.protobuf.AbstractParser<TestData>() {
      public TestData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SN_FIELD_NUMBER = 1;
    private int sn_;
    /**
     * <code>required int32 sn = 1;</code>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 sn = 1;</code>
     */
    public int getSn() {
      return sn_;
    }

    private void initFields() {
      sn_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sn_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocolBuffer.TestData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocolBuffer.TestData)
        co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.solinx.demo.serialize.protocolBuffer.TestDataProto.internal_static_protocolBuffer_TestData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.solinx.demo.serialize.protocolBuffer.TestDataProto.internal_static_protocolBuffer_TestData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData.class, co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData.Builder.class);
      }

      // Construct using co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.solinx.demo.serialize.protocolBuffer.TestDataProto.internal_static_protocolBuffer_TestData_descriptor;
      }

      public co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData getDefaultInstanceForType() {
        return co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData.getDefaultInstance();
      }

      public co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData build() {
        co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData buildPartial() {
        co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData result = new co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sn_ = sn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData) {
          return mergeFrom((co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData other) {
        if (other == co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData.getDefaultInstance()) return this;
        if (other.hasSn()) {
          setSn(other.getSn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSn()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (co.solinx.demo.serialize.protocolBuffer.TestDataProto.TestData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sn_ ;
      /**
       * <code>required int32 sn = 1;</code>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 sn = 1;</code>
       */
      public int getSn() {
        return sn_;
      }
      /**
       * <code>required int32 sn = 1;</code>
       */
      public Builder setSn(int value) {
        bitField0_ |= 0x00000001;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sn = 1;</code>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sn_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocolBuffer.TestData)
    }

    static {
      defaultInstance = new TestData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocolBuffer.TestData)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocolBuffer_TestData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocolBuffer_TestData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016TestData.proto\022\016protocolBuffer\"\026\n\010Test" +
      "Data\022\n\n\002sn\030\001 \002(\005B8\n\'co.solinx.demo.seria" +
      "lize.protocolBufferB\rTestDataProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocolBuffer_TestData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocolBuffer_TestData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocolBuffer_TestData_descriptor,
        new java.lang.String[] { "Sn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
